### ISSUE TITLE
create bindings for raymath

### ISSUE THREAD

**Issue by Skytrias** [kevinw/raylib-odin#1]
The bindings for raylib are awesome so far, they work besides the missing implementations of raymath. I think theyre the most important to add to get people to use these bindings.

Since odin has vec2 and mat4 as well you said you had to decide which one to use, either odins or raylibs implementation.

I'd you should just bind the raymath implementation since it also has some functions the odin math doesnt have like clamp or perpendicular vector2/vector3.

**Comment by kevinw** [comment]
Added bindings in dfc0c5e5551af64460da809e264a20312632cd86.

That commit also makes Vector2, Vector3, Vector4, and Matrix all aliases for the odin `core/math` types, so we have the best of both worlds--you can use `core/math` functions, or `raylib` functions.

See [examples/example_raymath/example_raymath.odin](https://github.com/kevinw/raylib-odin/blob/master/examples/example_raymath/example_raymath.odin) for how to use!
