### ISSUE TITLE
Running On Linux

### ISSUE THREAD

**Issue by jayvinius** [kevinw/raylib-odin#4]
When trying to run on Linux the example programs fail to build because the linker is failing to find raylib.lib.
Here are the exact errors called:
```
/usr/bin/ld: cannot find -l/home/batman/dev/raylib-odin/lib/raylib.lib
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```
I am not knowledgeable about Odin to try and fix this myself. Any help is greatly appreciated.

**Comment by ustance** [comment]
Had the same problem.
I made it work by installing raylib from repository and changing raylib_binding import to `system:raylib`

Not the best solution, but you can get something working with it.

**Comment by alstrup** [comment]
When I try that syntax, I get this now:
 Syntax Error: The library collection 'system' is restrict for 'foreign_library'
 Any ideas?

**Comment by kevinw** [comment]
The syntax for importing libraries has changed recently--check `CHANGELOG.txt` in the Jai compiler! I don't have time currently to keep this project up to date, but I'm happy to accept pull requests for fixes.

**Comment by a-y-u-s-h** [comment]
Any solutions to this yet?

**Comment by kevinw** [comment]
@a-y-u-s-h this repo is now being updated here IMO https://github.com/ftommasi/raylib-odin
